version: '3.8'

services:
  aso-playwright-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - ASO_EMAIL=${ASO_EMAIL}
      - ASO_PASSWORD=${ASO_PASSWORD}
      - ASO_APP_NAME=${ASO_APP_NAME}
      - BROWSER_CAT_API_KEY=${BROWSER_CAT_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s